# docker-compose.yml

version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: spectre-postgres
    environment:
      POSTGRES_DB: spectre
      POSTGRES_USER: spectre
      POSTGRES_PASSWORD: spectre
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "spectre"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

  app:
    container_name: spectre_app
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
    restart: no
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spectre
      SPRING_DATASOURCE_USERNAME: spectre
      SPRING_DATASOURCE_PASSWORD: spectre
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge