spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/spectre
    username: spectre
    password: spectre
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/initial/master_changelog.xml
    enabled: true